---
title: "assignment_3"
author: "Alicia Canales and Zoe Zhou"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cerulean
    code_folding: 'hide'
---

```{r setup, echo = TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(tidyverse)
library(here)
library(patchwork)
```

# Profit model
```{r}
source('../functions/compute_crop_yield.R')
source('../functions/compute_profit.R')
climate_data <- read.table(here('data', 'clim.txt'), header = TRUE)

almond_profit <- compute_profit(climate_data)
```

# Informal Sensitivity Model for Cost
```{r}
## 
cost_var <- rnorm(mean = 7, sd = 0.1, n = 20)

cost_sensitivity <- map(cost_var, ~compute_profit(climate_data, cost = cost_var))
head(cost_sensitivity)

cost_sen <- map_df(cost_sensitivity,`[`, c('year', 'profit')) 
```

# Informal Sensitivity Model for Irrigation
```{r}
labor <- rnorm(mean = 10, sd = 0.1, n = 20) 

labor_sensitivity <- map(labor, ~compute_profit(climate_data, labor = labor))
head(labor_sensitivity)

labor_sen <- map_df(labor_sensitivity,`[`, c('year', 'profit')) 
```

# plots
```{r}
## Cost Plot
p1 <- ggplot(cost_sen, aes(year, profit, group = year)) +
  geom_boxplot(fill = 'blue') +
  labs(x = 'Year', y = "Total Profit of Almond Sales ($) ") +
  ggtitle('Sensitivity Analysis of Cost') +
  theme_minimal()


## Labor Plot
p2 <- ggplot(labor_sen, aes(year, profit, group = year)) +
  geom_boxplot(fill = 'orange') +
  labs(x = 'Year', y = "Total Profit of Almond Sales ($) ") +
  ggtitle('Sensitivity Analysis of Labor') +
  theme_minimal()

p1+ p2 +
  plot_layout(ncol = 1,
              guides = 'collect')
```

*Write a short paragraph (in the Rmarkdown document) to summarize you interpretation of your model results (e.g what do 'take away' from your model and sensitivity analysis) *
