---
title: "Assignment_5"
author: "Alicia Canales & Zoe Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, echo = TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sensitivity)
library(tidyverse)
library(here)
library(purrr)
library(ggpubr)
```

### Reading and cleaning data for summer months
```{r}

## metric is high stream flow
sager = read.table(here('data', 'sager.txt'), header = TRUE)
head(sager)

## add date
sager = sager %>% 
  mutate(date = paste(day,month,year, sep="/"))

sager$date = as.Date(sager$date,"%d/%m/%Y")

## initial plot
sager_clean = sager %>% 
  pivot_longer(cols=c("model","obs"), names_to="source",
                                  values_to="flow") 

## subsetting only annual summer streamflow: june - august
annual_summer_flow <- sager_clean %>% 
  group_by(year, month, source) %>% 
  filter(month %in% c(5:8)) %>% 
  summarize(flow = sum(flow))


## plot of annual summer flow 
ggplot(annual_summer_flow, aes(year, flow, col = source, linetype = source)) +
  geom_line() +
  labs(x = 'Year', y = 'Annual Summer Streamflow') +
  scale_color_manual(values = c('blue', 'green4')) +
  theme_minimal()

```


### Developing a Combined Metric
```{r}
## performance metric using 
source('../functions/compute_low_flow.R')

## performance using compute low flow function
perf <- compute_lowflow(m=sager$model,o=sager$obs, month=sager$month, day=sager$day, year=sager$year, low_flow_months = c(6:8))

## making performance into a data frame
perf = as.data.frame((perf))

## transforming 'summer months' using maximum error
low_flow_months = sager %>% 
  subset(month %in% c(6:8))

## 50% of summer months observed low flow
annual_errmax = mean(low_flow_months$obs)*0.5
 
perf = perf %>% 
  mutate(annual_min_err_trans = max(0,(1-abs(annual_min_err/annual_errmax)))) 
 
## transforming 'annual summer months'      
tmp = sager %>% 
  subset(month %in% c(6:8)) %>%
  group_by(year, month) %>% 
  summarize(obs = sum(obs))

errmax = mean(tmp$obs)*0.5
 
perf = perf %>% 
  mutate(low_month_err_trans = max(0,(1-abs(low_month_err/errmax))))

## Combining the 4 metrics together 
perf = perf %>% 
  mutate(combined = (annual_min_cor + annual_min_err_trans + low_month_err_trans + low_month_cor)/4)

perf
```

### Split sample calibration
```{r}
## reading in data
source("../functions/nse.R") 
msage = read.table("../Data/sagerm.txt", header=T)

## saving the number of simulations
number_sim = ncol(msage)

## making names for each simulation
snames = sprintf("S%d",seq(from = 1, to = number_sim))

## adding names to the columns
colnames(msage) = snames

## adding the dates to this df
msage$date = sager$date
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day

## adding on the observed
msage = left_join(msage, sager[,c("obs","date")], by=c("date"))
head(msage)

## subsetting for the split sample
subset_msage = subset(msage, month %in% c(6:8))

## running performance on all parameters
split_perf = subset_msage %>% 
  select(-date, -month, -day, -year, -wy, -obs ) %>%
  map_df(compute_low_flow, o = subset_msage$obs, month = subset_msage$month, day = subset_msage$day, year = subset_msage$year)

## adding names to simulations
split_perf$sim = snames
head(split_perf)

```

