---
title: "catm_sensi_1"
author: "Alicia Canales"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sensitivity)
library(tidyverse)
library(lhs)
library(purrr)
library(here)
```

```{r}
# set a random seed to make things 'random'
set.seed(1)

# which parameters
pnames = c("height", "wind", "k_d", "k_0")

# how many parameters
npar =  length(pnames)
# how many samples
nsample = 100

## making the quantiles using latin hypercube
parm_quant = randomLHS(nsample, npar)

## renaming colnames
colnames(parm_quant) = pnames

## making an empty dataframe with the cleaned col names
parm <- as.data.frame(matrix(nrow=nrow(parm_quant), 
                             ncol=ncol(parm_quant)))
colnames(parm) = pnames

## to make it easy to change i'm setting standard deviation / range variation to a variable
pvar = 1
# choose distributions for parameters - this would come from what you know about the likely range of variation
parm[,"height"] = qnorm(parm_quant[,"height"], mean = 9)
parm[,"wind"] = qnorm(parm_quant[,"wind"], mean = 250, sd = 30)

# then use our random samples to pick the quantiles
parm[,"k_d"] = qunif(parm_quant[,"k_d"], min= 0.07 - 0.07/pvar, max= 0.07 + 0.07/pvar)
parm[,"k_0"] = qunif(parm_quant[,"k_0"], min= 0.01 - 0.1/pvar, max= 0.1 + 0.1/pvar)

# note I could also index by column number by names keep things more clear, fewer mistakes
#parm[,5] = qnorm(parm_quant[,5], mean=0.28, sd=0.28/pvar)

head(parm)
```

## Running model on parameters from LHS
```{r}
# lets now run our model for all of the parameters generated by LHS
# pmap is useful here - it is a map function that uses the actual names of input parameters

atm <- pmap(parm, ~Catm(.x))

# notice that what pmap returns is a list 
head(atm)

# turn results in to a dataframe for easy display/analysis
catm = do.call(rbind.data.frame, atm)
colnames(catm) <- 'ca'
```

## Plotting
```{r}
# add uncertainty bounds on our estimates
tmp = atm %>% gather(value="value", key="yield")

ggplot(tmp, aes(yield, value, col=yield))+geom_boxplot()+
  labs(y="Yield (as anomoly)")

# note that you don't see the ranges because of the scale (min yield anomoly much smaller than max) - here's a more informative way to graph
ggplot(tmp, aes(yield, value, col=yield))+
  geom_boxplot()+labs(y="Yield (as anomoly)")+
  facet_wrap(~yield, scales="free" )


# cumulative distribution
ggplot(yieldsd, aes(maxyield))+stat_ecdf()
```

## Quantifying Results
```{r}
result = map(parm, cor.test, y = catm$ca)
result$height
result$wind
result$k_d
result$k_0


# just the confidence interval
justconf = result %>% map_df("conf.int")
justconf

# partial regression rank coefficients

senresult_rank = pcc(parm, catm$ca, rank=TRUE )
senresult_rank
plot(senresult_rank)

# k_o = 0.95
# k_d = 0.42
# v = 0.95
# height = 0.42?
```

